Upgrade to labeler 5.0.0
frequenz-floss/frequenz-repo-config-python pull request #211
Opened 2024-01-02 10:36 UTC by llucax

This also fix the matching rules, that were broken, probably because the version before 5.0.0 didn't support the flexible glob matching or it was misused.

2024-01-29 13:21 UTC, Marenz requested changes

2024-01-29 13:21 UTC, Marenz commented on RELEASE_NOTES.md
> +    If you didn't diverged much from the default configuration (and you are not using exclusion rules), you can update the configution file by running this script in the root of your repository:
*`didn't diverge ` or `haven't diverged`

2024-01-29 13:21 UTC, Marenz commented on RELEASE_NOTES.md
> +    If you didn't diverged much from the default configuration (and you are not using exclusion rules), you can update the configution file by running this script in the root of your repository:
`configution` => `configuration`

2024-01-31 16:47 UTC, llucax commented on RELEASE_NOTES.md
> +    If you didn't diverged much from the default configuration (and you are not using exclusion rules), you can update the configution file by running this script in the root of your repository:
Updated to fix both typos. Thanks!

2024-01-31 17:04 UTC, Marenz approved these changes

2024-01-31 17:12 UTC, merged