ci: Support using git for dependencies in `test-installation`
frequenz-floss/frequenz-repo-config-python pull request #222
Opened 2024-02-07 18:28 UTC by Marenz

Fix the CI test that fails when dependencies in pyproject.toml contain git urls.

I didn't have time to update the tests, feel free to take over.

2024-02-08 11:56 UTC, llucax commented
Updating the tests should be just: `UPDATE_GOLDEN=1 pytest tests/integration/test_cookiecutter_generation.py::test_golden`.

Ideally this repo should get the fix.

I plan to dedicate some time to repo-config in a not so distant future, if you didn't take care of it until then I can take it over.

2024-02-08 11:57 UTC, llucax requested changes
Marking as needing changes so it is more obvious in the PR list. Basically this needs:

- Update this project with the fix
- Fix tests
- Split the cleaning of the docker image in its own commit
- Improve the commit description a bit

2024-02-19 15:42 UTC, llucax submitted a review, later dismissed

2024-02-19 15:42 UTC, llucax commented
OK, I took over this one and updated with the missing stuff. But now it needs an approval from someone else :)

2024-02-19 16:13 UTC, Marenz commented
Yeah, I can't approve this, being the author and all.

2024-02-19 16:47 UTC, cwasicki approved these changes

2024-02-20 08:16 UTC, leandro-lucarella-frequenz approved these changes

2024-02-20 10:50 UTC, shsms approved these changes

2024-02-20 10:58 UTC, merged